# -*- coding: utf-8 -*-
"""korus70_smartcity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eWE5JD1iShqbwu-0rf2WdV6wcDXasDFG

# KORUS70 Smart City — Traffic & Air Quality (Orlando Metro)
## AI/Data-Science analysis of traffic–weather–transit drivers of PM2.5 & NO2

**Refactored, reproducible Colab notebook.**

This notebook predicts **daily air-quality (PM2.5 and NO2)** at EPA monitoring stations
in the Orlando metro from **traffic volume, weather, transit accessibility, and time features**,
and produces a **vulnerability map** of traffic-count locations.

### Honest scope note (read first)
The available data contain very few spatial units in the study area:
- **5 PM2.5 stations**, **3 NO2 stations** (EPA)
- **5 FDOT traffic count sites** in Orange County (2 directions each)

That is far too few *locations* to learn a credible **spatial** cross-sectional model
(predicting "why is station A dirtier than station B"). With ~5 points, a Random Forest will
memorize station identity and report meaningless feature importances.

So this notebook reframes the task honestly as a **temporal / panel prediction**:
> *Given a station and a day, predict that day's pollutant level from that day's traffic,
> weather, season, and the station's fixed transit context.*

The unit of analysis is therefore the **(station × day)** record. Validation is done by
**time-based split** (train on earlier dates, test on later dates) to avoid leakage. We also
report a **GroupKFold-by-station** sensitivity check. Spatial conclusions are presented as
**descriptive maps**, not as model claims.
"""

# %% [1] Library install (Colab)
!pip -q install geopandas
!pip -q install matplotlib
!pip install scikit-learn

# %% [2] Imports & global config
import os, zipfile, shutil, warnings, json
from pathlib import Path
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import Ridge
from sklearn.dummy import DummyRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import GroupKFold, cross_val_predict
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.inspection import permutation_importance

try:
    from xgboost import XGBRegressor
    XGBOOST_AVAILABLE = True
except Exception:
    XGBOOST_AVAILABLE = False
print("XGBoost available:", XGBOOST_AVAILABLE)

RANDOM_STATE = 42

# --- Coordinate reference systems --------------------------------------------
# Verified from the data:
#   * EPA lat/lon  -> EPSG:4326 (geographic, degrees)
#   * FDOT x/y     -> EPSG:26917 (UTM 17N, metres)  [verified: y ~3.15e6 m, not feet]
#   * BusStops .prj-> NAD83 State Plane Florida East, US feet (EPSG:2236)
# We project EVERYTHING to a single metric CRS for distance/buffer maths.
WORK_CRS = "EPSG:26917"     # UTM 17N, metres  -> all buffers below are in METRES
EPA_CRS     = "EPSG:4326"
TRAFFIC_CRS = "EPSG:26917"

TARGET_COUNTIES = ["Orange", "Seminole", "Osceola"]   # Orlando CBSA core

# Transit buffers around each AIR-QUALITY station (metres)
BUS_BUFFERS_M = {"500m": 500, "1km": 1000, "3km": 3000}

# Traffic->air-station linkage
TRAFFIC_BUFFER_M  = 5000     # link traffic sites within 5 km of a station ...
NEAREST_TRAFFIC_K = 3        # ... else fall back to the K nearest sites

OUTPUT_DIR = Path("outputs"); OUTPUT_DIR.mkdir(exist_ok=True)
print("Output dir:", OUTPUT_DIR.resolve(), "| Work CRS:", WORK_CRS)

import os
print(os.getcwd())
print(os.listdir("."))
from google.colab import files
uploaded = files.upload()

# %% [3] 입력 파일 탐색 — PM2.5/NO2는 연도별 여러 파일을 모두 수집
from pathlib import Path

def list_all_files():
    files = [p for p in Path(".").rglob("*")
             if p.is_file() and p.suffix.lower() in (".csv", ".zip")]
    print("현재 세션 데이터 파일:")
    for p in files: print("   -", p)
    return files

def find_one(keywords, ext=".csv"):
    kws = [k.lower() for k in keywords]
    for p in Path(".").rglob(f"*{ext}"):
        if all(k in p.name.lower() for k in kws):
            return p
    list_all_files()
    raise FileNotFoundError(f"키워드 {keywords} ({ext}) 매칭 실패")

# 연도별 여러 파일을 모두 반환
def find_many(keywords, ext=".csv"):
    kws = [k.lower() for k in keywords]
    hits = sorted(p for p in Path(".").rglob(f"*{ext}")
                  if all(k in p.name.lower() for k in kws))
    if not hits:
        list_all_files()
        raise FileNotFoundError(f"키워드 {keywords} ({ext}) 매칭 실패")
    return hits

list_all_files()

WEATHER_PATH = find_one(["weather"])
TRAFFIC_PATH = find_one(["traffic", "tmscount"])
BUS_ZIP_PATH = find_one(["busstops"], ext=".zip")

# PM2.5 / NO2 는 연도별 파일 '리스트'로 받음
PM25_PATHS = find_many(["pm2", "epa"])   # PM2_5_2023..2026
NO2_PATHS  = find_many(["no2", "epa"])   # NO2_2023..2026

print("\nPM2.5 파일:", [p.name for p in PM25_PATHS])
print("NO2  파일:", [p.name for p in NO2_PATHS])
print("weather :", WEATHER_PATH.name, "| traffic:", TRAFFIC_PATH.name, "| bus:", BUS_ZIP_PATH.name)

# %% [4] Unzip BusStops and auto-discover the .shp
BUS_DIR = Path("data/bus_stops"); BUS_DIR.mkdir(parents=True, exist_ok=True)
with zipfile.ZipFile(BUS_ZIP_PATH) as z:
    z.extractall(BUS_DIR)

shp_hits = sorted(BUS_DIR.rglob("*.shp"))
if not shp_hits:
    raise FileNotFoundError("No .shp found inside the BusStops zip.")
BUS_SHP = shp_hits[0]
print("Bus stop shapefile:", BUS_SHP)

# %% [5] CSV 로드 — 연도별 EPA 파일을 합쳐서 읽고 구조 확인
import pandas as pd

weather = pd.read_csv(WEATHER_PATH)
traffic = pd.read_csv(TRAFFIC_PATH)

# 연도별 PM2.5/NO2 파일을 하나로 결합 (컬럼 동일함을 이미 확인)
def load_and_concat(paths, label):
    frames = []
    for p in paths:
        d = pd.read_csv(p)
        d["source_file"] = p.name          # 어느 연도 파일인지 추적용
        frames.append(d)
        print(f"  {p.name}: {len(d)}행")
    combined = pd.concat(frames, ignore_index=True)
    # 같은 날·같은 site·같은 POC 중복 가능성 제거 (연도 경계 안전장치)
    before = len(combined)
    combined = combined.drop_duplicates(subset=["Date", "Site ID", "POC"])
    print(f"{label} 합계: {before}행 → 중복제거 후 {len(combined)}행 "
          f"| site {combined['Site ID'].nunique()}개\n")
    return combined

print("PM2.5 연도별 로드:")
pm25 = load_and_concat(PM25_PATHS, "PM2.5")
print("NO2 연도별 로드:")
no2 = load_and_concat(NO2_PATHS, "NO2")

for name, df in [("WEATHER", weather), ("PM2.5", pm25), ("NO2", no2), ("TRAFFIC", traffic)]:
    print("="*70); print(name, "shape:", df.shape)
    print("columns:", list(df.columns)); display(df.head(3))

# %% [6] Inspect the bus-stop shapefile (CRS + columns) before any spatial op
bus_raw = gpd.read_file(BUS_SHP)
print("Bus stops:", bus_raw.shape)
print("Original CRS:", bus_raw.crs)
print("columns:", list(bus_raw.columns))
display(bus_raw.drop(columns="geometry").head(3))
if bus_raw.crs is None:
    raise ValueError("Bus stop layer has no CRS (.prj missing).")

# %% [7] Parse dates consistently
# Weather dates are ISO (YYYY-MM-DD); EPA dates are MM/DD/YYYY; FDOT BEGDATE has a time part.
weather["date"] = pd.to_datetime(weather["date"]).dt.normalize()
pm25["date"]    = pd.to_datetime(pm25["Date"], format="%m/%d/%Y").dt.normalize()
no2["date"]     = pd.to_datetime(no2["Date"],  format="%m/%d/%Y").dt.normalize()
traffic["date"] = pd.to_datetime(traffic["BEGDATE"]).dt.normalize()

print("Date coverage")
for n, d in [("weather", weather), ("pm25", pm25), ("no2", no2), ("traffic", traffic)]:
    print(f"  {n:8s} {d['date'].min().date()} -> {d['date'].max().date()}  ({d['date'].nunique()} days)")
print("\nWeather missing values:\n", weather.isna().sum().to_string())

# %% [8] Traffic preprocessing
#   - keep target counties
#   - One physical count site (COSITE) usually has 2 direction rows per day:
#     SUM the directional hourly columns to get a true two-way daily volume.
#   - derive AM / PM peak windows from the hourly HR* columns.
traffic = traffic[traffic["COUNTY"].isin(TARGET_COUNTIES)].copy()

HR_COLS = [f"HR{i}" for i in range(1, 25)]
# Hour labels HR1..HR24 -> clock hours 0..23 (HR1 = 00:00-01:00).
AM_PEAK = ["HR8", "HR9", "HR10"]    # 07:00-10:00
PM_PEAK = ["HR17", "HR18", "HR19"]  # 16:00-19:00

for c in HR_COLS + ["TOTVOL", "PEAKVOL", "TRUCKS"]:
    if c in traffic.columns:
        traffic[c] = pd.to_numeric(traffic[c], errors="coerce")

traffic["am_peak"] = traffic[AM_PEAK].sum(axis=1)
traffic["pm_peak"] = traffic[PM_PEAK].sum(axis=1)

# One site = one COSITE (stable physical id). Aggregate both directions per day.
traffic["traffic_site_key"] = traffic["COSITE"].astype(str)

traffic_daily = (traffic
    .groupby(["traffic_site_key", "COUNTY", "LOCALNAM", "date", "x", "y"], as_index=False)
    .agg(daily_total_traffic=("TOTVOL", "sum"),
         am_peak=("am_peak", "sum"),
         pm_peak=("pm_peak", "sum"),
         peak_volume=("PEAKVOL", "max"),
         truck_volume=("TRUCKS", "sum")))

print("Traffic rows kept:", traffic.shape[0], "| daily site-records:", traffic_daily.shape[0])
print("Distinct traffic sites by county:")
print(traffic_daily.groupby("COUNTY")["traffic_site_key"].nunique().to_string())
display(traffic_daily.head())

# %% [9] Build GeoDataFrames in a single metric CRS (UTM 17N)
# Traffic points
traffic_gdf = gpd.GeoDataFrame(
    traffic_daily,
    geometry=gpd.points_from_xy(traffic_daily["x"], traffic_daily["y"]),
    crs=TRAFFIC_CRS).to_crs(WORK_CRS)

# Bus stops (State Plane ft -> UTM m)
bus_stops = bus_raw.to_crs(WORK_CRS)

# EPA air-quality station points (one row per unique site)
def air_sites_gdf(df):
    s = (df[["Site ID", "Local Site Name", "County",
             "Site Latitude", "Site Longitude"]]
         .drop_duplicates()
         .rename(columns={"Site ID": "air_site_id",
                          "Local Site Name": "air_site_name",
                          "Site Latitude": "lat", "Site Longitude": "lon"}))
    g = gpd.GeoDataFrame(s, geometry=gpd.points_from_xy(s["lon"], s["lat"]),
                         crs=EPA_CRS).to_crs(WORK_CRS)
    return g

pm25_sites = air_sites_gdf(pm25)
no2_sites  = air_sites_gdf(no2)
print("PM2.5 stations:", len(pm25_sites), "| NO2 stations:", len(no2_sites),
      "| traffic sites:", traffic_gdf["traffic_site_key"].nunique(),
      "| bus stops:", len(bus_stops))

# %% [10] Transit-accessibility features per AIR station (fixed in time)
#  bus-stop counts within 500m/1km/3km + distance to nearest stop.
def bus_access_features(sites_gdf, bus_gdf, id_col="air_site_id"):
    out = sites_gdf[[id_col]].copy()
    for label, r in BUS_BUFFERS_M.items():
        buf = sites_gdf[[id_col, "geometry"]].copy()
        buf["geometry"] = buf.geometry.buffer(r)
        j = gpd.sjoin(bus_gdf[["geometry"]], buf, predicate="within", how="inner")
        cnt = j.groupby(id_col).size().rename(f"bus_count_{label}").reset_index()
        out = out.merge(cnt, on=id_col, how="left")
    near = gpd.sjoin_nearest(sites_gdf[[id_col, "geometry"]], bus_gdf[["geometry"]],
                             how="left", distance_col="nearest_bus_dist_m")
    near = near[[id_col, "nearest_bus_dist_m"]].drop_duplicates(id_col)
    out = out.merge(near, on=id_col, how="left")
    cnt_cols = [c for c in out.columns if c.startswith("bus_count_")]
    out[cnt_cols] = out[cnt_cols].fillna(0)
    return out

pm25_bus = bus_access_features(pm25_sites, bus_stops)
no2_bus  = bus_access_features(no2_sites,  bus_stops)
print("PM2.5 transit features:"); display(pm25_bus)
print("NO2 transit features:");  display(no2_bus)

# %% [11] Link each AIR station to nearby traffic sites, then build a
#         DISTANCE-WEIGHTED daily traffic feature for that station.
# Rationale: with so few sites, a fixed buffer may catch 0; we fall back to
# K-nearest. Inverse-distance weighting lets closer counters matter more.
def station_traffic_link(sites_gdf, traffic_gdf, buffer_m, k):
    uniq = (traffic_gdf[["traffic_site_key", "geometry"]]
            .drop_duplicates("traffic_site_key").reset_index(drop=True))
    rows = []
    for _, a in sites_gdf.iterrows():
        d = uniq.copy()
        d["dist_m"] = d.geometry.distance(a.geometry)
        near = d[d["dist_m"] <= buffer_m]
        method = "buffer"
        if near.empty:
            near = d.nsmallest(k, "dist_m"); method = "nearest_k"
        near = near.copy(); near["air_site_id"] = a["air_site_id"]; near["link_method"] = method
        rows.append(near[["air_site_id", "traffic_site_key", "dist_m", "link_method"]])
    return pd.concat(rows, ignore_index=True)

def station_daily_traffic(sites_gdf, traffic_gdf, buffer_m=TRAFFIC_BUFFER_M, k=NEAREST_TRAFFIC_K):
    link = station_traffic_link(sites_gdf, traffic_gdf, buffer_m, k)
    # inverse-distance weight (+1 m to avoid div/0)
    link["w"] = 1.0 / (link["dist_m"] + 1.0)
    tdf = traffic_gdf.drop(columns="geometry").merge(link, on="traffic_site_key", how="inner")
    metrics = ["daily_total_traffic", "am_peak", "pm_peak", "peak_volume", "truck_volume"]
    for m in metrics:
        tdf[m + "_w"] = tdf[m] * tdf["w"]
    g = tdf.groupby(["air_site_id", "date"])
    agg = g.apply(lambda x: pd.Series({
        **{f"traffic_{m}_wmean": x[m + "_w"].sum() / x["w"].sum() for m in metrics},
        "n_traffic_sites_linked": x["traffic_site_key"].nunique(),
        "mean_traffic_dist_m": x["dist_m"].mean(),
    })).reset_index()
    return agg, link

pm25_traffic, pm25_link = station_daily_traffic(pm25_sites, traffic_gdf)
no2_traffic,  no2_link  = station_daily_traffic(no2_sites,  traffic_gdf)
print("PM2.5 station-traffic links:"); display(pm25_link)
print("PM2.5 daily traffic features (sample):"); display(pm25_traffic.head())

# %% [12] Assemble the (station x day) modelling table
def build_dataset(air_df, sites_bus, sites_traffic, weather, pollutant, conc_col):
    df = air_df.rename(columns={"Site ID": "air_site_id",
                                "Local Site Name": "air_site_name",
                                "County": "county",
                                conc_col: "y_conc",
                                "Daily AQI Value": "y_aqi"})
    df = df[["date", "air_site_id", "air_site_name", "county",
             "Site Latitude", "Site Longitude", "y_conc", "y_aqi"]].copy()

    # temporal merges (exact date keys)
    df = df.merge(sites_traffic, on=["air_site_id", "date"], how="left")
    df = df.merge(sites_bus,     on="air_site_id",          how="left")
    df = df.merge(weather,       on="date",                 how="left")

    # calendar features
    df["month"]      = df["date"].dt.month
    df["weekday"]    = df["date"].dt.weekday
    df["is_weekend"] = (df["weekday"] >= 5).astype(int)
    df["doy"]        = df["date"].dt.dayofyear
    # cyclical season encoding (better than raw day-of-year for trees+linear)
    df["doy_sin"] = np.sin(2*np.pi*df["doy"]/365.25)
    df["doy_cos"] = np.cos(2*np.pi*df["doy"]/365.25)

    # lagged pollutant (autocorrelation is a strong, legitimate predictor)
    df = df.sort_values(["air_site_id", "date"])
    df["y_lag1"] = df.groupby("air_site_id")["y_conc"].shift(1)
    df["pollutant"] = pollutant
    return df.reset_index(drop=True)

pm25_data = build_dataset(pm25, pm25_bus, pm25_traffic, weather, "pm25", "Daily Mean PM2.5 Concentration")
no2_data  = build_dataset(no2,  no2_bus,  no2_traffic,  weather, "no2",  "Daily Max 1-hour NO2 Concentration")

print("PM2.5 modelling table:", pm25_data.shape, "| NO2:", no2_data.shape)
display(pm25_data.head())
print("Missing per column (PM2.5):\n", pm25_data.isna().sum().to_string())

# %% [13] Feature set + leakage-safe, time-ordered modelling
TRAFFIC_FEATS = ["traffic_daily_total_traffic_wmean", "traffic_am_peak_wmean",
                 "traffic_pm_peak_wmean", "traffic_peak_volume_wmean",
                 "traffic_truck_volume_wmean", "n_traffic_sites_linked",
                 "mean_traffic_dist_m"]
BUS_FEATS     = ["bus_count_500m", "bus_count_1km", "bus_count_3km", "nearest_bus_dist_m"]
WEATHER_FEATS = ["AWND", "PRCP", "TMAX", "TMIN", "TAVG"]
TIME_FEATS    = ["month", "weekday", "is_weekend", "doy_sin", "doy_cos"]
LAG_FEATS     = ["y_lag1"]
ALL_FEATS     = TRAFFIC_FEATS + BUS_FEATS + WEATHER_FEATS + TIME_FEATS + LAG_FEATS

def time_split(df, frac=0.8):
    """날짜 기준 80/20 분할 (시간 누수 방지). 앞 기간=train, 뒤 기간=test."""
    df = df.dropna(subset=["y_conc"]).sort_values("date").reset_index(drop=True)
    cut = df["date"].quantile(frac)
    return df[df["date"] <= cut].copy(), df[df["date"] > cut].copy(), cut

def make_pipe(model, feats):
    """결측치 중앙값 대체 + 표준화 + 모델을 하나의 파이프라인으로."""
    pre = ColumnTransformer([("num", Pipeline([
        ("imp", SimpleImputer(strategy="median")),
        ("sc",  StandardScaler())]), feats)], remainder="drop")
    return Pipeline([("pre", pre), ("model", model)])

def metrics(y, p):
    return {"RMSE": mean_squared_error(y, p) ** 0.5,
            "MAE":  mean_absolute_error(y, p),
            "R2":   r2_score(y, p)}

def run(df, pollutant, feat_list=None):
    """주어진 feature 집합으로 Baseline/Ridge/RF/XGBoost를 학습·평가한다.
    반환: (성능표 DataFrame, 학습된 모델 dict, (train, test, feats))."""
    feats = [c for c in (feat_list or ALL_FEATS) if c in df.columns]
    train, test, cut = time_split(df)
    print(f"[{pollutant}] train={len(train)}  test={len(test)}  split_date={cut.date()}")
    if len(test) < 10 or len(train) < 30:
        print(f"  !! Not enough rows for a reliable {pollutant} model.")

    Xtr, ytr = train[feats], train["y_conc"]
    Xte, yte = test[feats],  test["y_conc"]

    models = {
        "Baseline(mean)": DummyRegressor(strategy="mean"),
        "Ridge":          Ridge(alpha=1.0),
        "RandomForest":   RandomForestRegressor(n_estimators=400, max_depth=6,
                                                min_samples_leaf=5, random_state=RANDOM_STATE,
                                                n_jobs=-1),
    }
    if XGBOOST_AVAILABLE:
        models["XGBoost"] = XGBRegressor(n_estimators=400, max_depth=4, learning_rate=0.05,
                                         subsample=0.8, colsample_bytree=0.8,
                                         random_state=RANDOM_STATE, n_jobs=-1)

    rows, fitted = [], {}
    for name, m in models.items():
        pipe = make_pipe(m, feats)
        pipe.fit(Xtr, ytr)
        pred = pipe.predict(Xte)
        r = metrics(yte, pred); r["model"] = name
        rows.append(r); fitted[name] = pipe

    res = pd.DataFrame(rows)[["model", "RMSE", "MAE", "R2"]]
    print(res.to_string(index=False))
    return res, fitted, (train, test, feats)

# ─────────────────────────────────────────────────────────────────────
# 대표 모델만 1회 학습한다 (전체 데이터, 전체 변수).
# 뒤 셀들(permutation importance·plots)이 이 pm25_fit/pm25_split을 참조한다.
# lag 제외 비교 / 트랙 A·B 분리 / CSV 저장은 모두 셀 13b~13e에서 수행한다.
# ─────────────────────────────────────────────────────────────────────
pm25_res, pm25_fit, pm25_split = run(pm25_data, "PM2.5")
no2_res,  no2_fit,  no2_split  = run(no2_data,  "NO2")

# %% [13b] 두 트랙 분리 — 데이터 가용성에 맞춘 분석 설계
# ─────────────────────────────────────────────────────────────────────────
# 배경: FDOT TMSCOUNT는 '최근 6개월 롤링' 데이터만 공개하므로, 일별 교통량은
#       2025-06 이후 구간에만 존재한다. 2023~2024 대기질 행의 교통 변수는
#       구조적으로 결측(NaN)이다 (구할 수 없는 데이터).
# 따라서 분석을 두 트랙으로 나눈다:
#   • 트랙 A (장기, 2023~2026): 교통 변수 제외. lag·기상·계절로 대기질 장기 변동 설명.
#                               표본이 크고 안정적. → 주력 예측 모델.
#   • 트랙 B (단기, 2025~2026): 교통 변수 포함. '교통 → 대기질' 영향에 집중.
#                               표본은 작지만 과제 핵심 질문에 직접 답한다.
# ─────────────────────────────────────────────────────────────────────────

# 교통 변수를 뺀 feature 집합 (트랙 A용). 버스 접근성은 시간불변이라 유지.
FEATS_NO_TRAFFIC = [f for f in ALL_FEATS if f not in TRAFFIC_FEATS]

def split_tracks(df):
    """교통 변수 존재 여부로 단기(B) 구간을 분리한다."""
    has_traffic = df["traffic_daily_total_traffic_wmean"].notna()
    track_b = df[has_traffic].copy()               # 교통 데이터가 있는 기간만
    return df, track_b                              # (전체=트랙A 후보, 트랙B)

pm25_all, pm25_tb = split_tracks(pm25_data)
no2_all,  no2_tb  = split_tracks(no2_data)

print("데이터 가용성 점검")
for name, full, tb in [("PM2.5", pm25_all, pm25_tb), ("NO2", no2_all, no2_tb)]:
    print(f"  {name}: 전체 {len(full)}행 "
          f"| 교통 포함 기간 {len(tb)}행 "
          f"({tb['date'].min().date()} ~ {tb['date'].max().date()})")

# %% [13c] 트랙 A — 장기 대기질 모델 (2023~2026, 교통 변수 제외)
# lag 포함 / lag 제외를 둘 다 보고하여 '계절·자기상관' vs '순수 환경요인' 기여를 분리.
print("="*70, "\n[트랙 A] 장기 모델 — 교통 제외, lag 포함")
# 트랙 A
pm25_A, pm25_fit_A, pm25_split_A = run(pm25_all, "PM2.5 (A, +lag)", feat_list=FEATS_NO_TRAFFIC)
no2_A,  no2_fit_A,  no2_split_A  = run(no2_all,  "NO2 (A, +lag)",  feat_list=FEATS_NO_TRAFFIC)

print("="*70, "\n[트랙 A] 장기 모델 — 교통 제외, lag 제외 (기상·계절만)")
FEATS_A_NOLAG = [f for f in FEATS_NO_TRAFFIC if f != "y_lag1"]
pm25_A_nolag, _, _ = run(pm25_all, "PM2.5 (A, -lag)", feat_list=FEATS_A_NOLAG)
no2_A_nolag,  _, _ = run(no2_all,  "NO2 (A, -lag)",  feat_list=FEATS_A_NOLAG)

# %% [13d] 트랙 B — 교통-환경 결합 모델 (2025~2026, 교통 변수 포함)
# 과제 핵심 질문: "교통량이 대기질에 영향을 주는가?"
# 교통 포함 / 교통+lag 제외를 비교하면 교통 변수의 순수 기여를 읽을 수 있다.
print("="*70, "\n[트랙 B] 단기 모델 — 교통 포함 (전체 변수)")
pm25_B,      pm25_fit_B, pm25_split_B = run(pm25_tb, "PM2.5 (B, all)", feat_list=ALL_FEATS)
no2_B,       no2_fit_B,  no2_split_B  = run(no2_tb,  "NO2 (B, all)",  feat_list=ALL_FEATS)

print("="*70, "\n[트랙 B] 단기 모델 — 교통·lag 제외 (기상·계절·버스만 = 교통 기여 측정용 기준선)")
FEATS_B_BASE = [f for f in ALL_FEATS if f not in TRAFFIC_FEATS and f != "y_lag1"]
pm25_B_base, _, _ = run(pm25_tb, "PM2.5 (B, base)", feat_list=FEATS_B_BASE)
no2_B_base,  _, _ = run(no2_tb,  "NO2 (B, base)",  feat_list=FEATS_B_BASE)

# %% [13e] 두 트랙 결과를 하나의 비교표로 정리하고 저장
def tag(res, pollutant, track, variant):
    r = res.copy()
    r["pollutant"] = pollutant; r["track"] = track; r["variant"] = variant
    return r

summary = pd.concat([
    tag(pm25_A,       "PM2.5", "A_long_2023_2026",  "with_lag_no_traffic"),
    tag(pm25_A_nolag, "PM2.5", "A_long_2023_2026",  "no_lag_no_traffic"),
    tag(pm25_B,       "PM2.5", "B_short_2025_2026", "all_features"),
    tag(pm25_B_base,  "PM2.5", "B_short_2025_2026", "no_traffic_no_lag"),
    tag(no2_A,        "NO2",   "A_long_2023_2026",  "with_lag_no_traffic"),
    tag(no2_A_nolag,  "NO2",   "A_long_2023_2026",  "no_lag_no_traffic"),
    tag(no2_B,        "NO2",   "B_short_2025_2026", "all_features"),
    tag(no2_B_base,   "NO2",   "B_short_2025_2026", "no_traffic_no_lag"),
], ignore_index=True)

summary = summary[["pollutant", "track", "variant", "model", "RMSE", "MAE", "R2"]]
summary.to_csv(OUTPUT_DIR / "model_results_two_track.csv", index=False)
print("두 트랙 통합 결과 (Ridge·RandomForest만 발췌):")
print(summary[summary["model"].isin(["Ridge", "RandomForest"])].to_string(index=False))

# %% [14] Permutation importance (model-agnostic, computed on the TEST set)
# Tree 'feature_importances_' are biased toward high-cardinality features;
# permutation importance on held-out data is the defensible choice.
def perm_importance(fitted, split, pollutant, model_name="RandomForest"):
    train, test, feats = split
    if model_name not in fitted: return pd.DataFrame()
    pipe = fitted[model_name]
    r = permutation_importance(pipe, test[feats], test["y_conc"],
                               n_repeats=20, random_state=RANDOM_STATE, n_jobs=-1)
    fi = (pd.DataFrame({"feature": feats, "importance": r.importances_mean,
                        "std": r.importances_std})
          .sort_values("importance", ascending=False).reset_index(drop=True))
    fi["pollutant"] = pollutant; fi["model"] = model_name
    return fi

# 트랙 A (장기, 교통 제외): lag·기상·계절 중 무엇이 중요한지
pm25_fi_A = perm_importance(pm25_fit_A, pm25_split_A, "PM2.5")
no2_fi_A  = perm_importance(no2_fit_A,  no2_split_A,  "NO2")

# 트랙 B (단기, 교통 포함): ★ 교통 변수의 실제 중요도 — 과제 핵심
pm25_fi_B = perm_importance(pm25_fit_B, pm25_split_B, "PM2.5")
no2_fi_B  = perm_importance(no2_fit_B,  no2_split_B,  "NO2")

print("="*60, "\n[트랙 A · 장기 · 교통 제외] PM2.5 변수중요도"); display(pm25_fi_A.head(10))
print("[트랙 A · 장기 · 교통 제외] NO2 변수중요도");            display(no2_fi_A.head(10))
print("="*60, "\n[트랙 B · 단기 · 교통 포함] PM2.5 변수중요도 ★"); display(pm25_fi_B.head(10))
print("[트랙 B · 단기 · 교통 포함] NO2 변수중요도 ★");           display(no2_fi_B.head(10))

# 뒤쪽 플롯 셀(15)이 참조하는 기본 변수는 트랙 B 기준으로 둔다 (과제 주제 정렬)
pm25_fi, no2_fi = pm25_fi_B, no2_fi_B

# %% [15] Plots: predicted vs actual (time) + feature importance
def plot_importance(fi, pollutant):
    if fi.empty: return
    top = fi.head(12).sort_values("importance")
    plt.figure(figsize=(9, 6))
    plt.barh(top["feature"], top["importance"], xerr=top["std"])
    plt.title(f"{pollutant} — permutation importance (test set)")
    plt.xlabel("Mean decrease in R2 when shuffled"); plt.tight_layout()
    plt.savefig(OUTPUT_DIR / f"{pollutant.lower()}_importance.png", dpi=200)
    plt.show()

def plot_pred(fitted, split, pollutant, model_name="RandomForest"):
    train, test, feats = split
    if model_name not in fitted: return
    pred = fitted[model_name].predict(test[feats])
    t = test.sort_values("date")
    plt.figure(figsize=(11, 4))
    plt.plot(t["date"], t["y_conc"], label="actual", marker=".", lw=1)
    plt.plot(t["date"], fitted[model_name].predict(t[feats]),
             label=f"{model_name} predicted", marker=".", lw=1)
    plt.title(f"{pollutant} — actual vs predicted (held-out period)")
    plt.legend(); plt.tight_layout()
    plt.savefig(OUTPUT_DIR / f"{pollutant.lower()}_pred_vs_actual.png", dpi=200)
    plt.show()

plot_importance(pm25_fi, "PM2.5"); plot_pred(pm25_fit, pm25_split, "PM2.5")
plot_importance(no2_fi,  "NO2");   plot_pred(no2_fit,  no2_split,  "NO2")

# %% [15b] Census ACS (census tract) 형평성 데이터 결합
# .gdb 안에 tract 경계 + ACS 변수(인구·소득·차량보유)가 함께 들어있음.
import glob
gdb_path = glob.glob("**/cenacs_2024.gdb", recursive=True)
if not gdb_path:
    # zip이 아직 안 풀렸으면 풀기
    import zipfile
    zsrc = find_one(["cenacs"], ext=".zip")
    zipfile.ZipFile(zsrc).extractall("data/acs")
    gdb_path = glob.glob("**/cenacs_2024.gdb", recursive=True)
GDB = gdb_path[0]; print("ACS gdb:", GDB)

# 레이어 목록 확인 (pyogrio 사용)
import pyogrio
print("레이어:", pyogrio.list_layers(GDB))

acs = gpd.read_file(GDB)          # 보통 단일 레이어
print("ACS shape:", acs.shape)
print("columns:", list(acs.columns))    # ★ 실제 컬럼명 먼저 확인
display(acs.drop(columns="geometry").head(2))

# %% [15c] tract 형평성 지표 계산 + 연구 지역만 필터  (수정판)
# 이 데이터의 COUNTY는 이름이 아니라 FIPS 코드라서, GEOID20 앞자리로 필터한다.
# GEOID20 = 2자리 주(State) + 3자리 카운티(County) + 6자리 tract.
# Florida=12, Orange=095, Seminole=117, Osceola=097
COL = {
    "geoid":   "GEOID20",
    "medinc":  "MEDHHINC",      # 가구 중위소득 (실측 컬럼 확인됨)
    "veh0":    "VEHICLE_0",     # 차량 0대 가구 수 (확인됨)
    "hh":      "HOUSEHOLDS",    # 총가구 수 (확인됨)
    "below":   "BELOW_POV",     # 빈곤선 이하 인구 (확인됨)
    "above":   "ABOVE_POV",     # 빈곤선 이상 인구 (확인됨)
    "pop":     "TOTALPOP",      # 총인구 (확인됨; TOTPOP 아님)
}

acs = acs.to_crs(WORK_CRS)

# ★ 핵심 수정: GEOID20 앞 5자리(주+카운티 FIPS)로 올랜도 권역 필터
TARGET_FIPS = {"12095": "Orange", "12117": "Seminole", "12097": "Osceola"}
acs["county_fips"] = acs[COL["geoid"]].astype(str).str[:5]
acs_study = acs[acs["county_fips"].isin(TARGET_FIPS)].copy()
acs_study["county_name"] = acs_study["county_fips"].map(TARGET_FIPS)

# 파생 지표 계산
# (1) 차량 없는 가구 비율 (%) — 대중교통 의존도 = 취약성 핵심
acs_study["pct_no_vehicle"] = 100 * acs_study[COL["veh0"]] / acs_study[COL["hh"]].replace(0, np.nan)
# (2) 빈곤율 (%) — PCT_POV가 없으므로 직접 계산
denom_pov = (acs_study[COL["below"]] + acs_study[COL["above"]]).replace(0, np.nan)
acs_study["pct_poverty"] = 100 * acs_study[COL["below"]] / denom_pov

print("연구지역 tract 수:", len(acs_study))      # ★ 이제 0이 아니어야 함
print(acs_study["county_name"].value_counts().to_string())
display(acs_study[[COL["geoid"], "county_name", COL["medinc"],
                   "pct_poverty", "pct_no_vehicle"]].head())

# %% [16] Descriptive vulnerability index at TRAFFIC count locations
# NOTE: this is a transparent weighted index, NOT a model prediction.
# vulnerability = high traffic burden + poor transit access.
def traffic_site_summary(traffic_gdf, bus_gdf):
    sites = (traffic_gdf.groupby(["traffic_site_key", "COUNTY", "LOCALNAM"])
             .agg(mean_daily_traffic=("daily_total_traffic", "mean"),
                  mean_truck=("truck_volume", "mean"))
             .reset_index())
    geom = traffic_gdf.drop_duplicates("traffic_site_key")[["traffic_site_key", "geometry"]]
    sites = gpd.GeoDataFrame(sites.merge(geom, on="traffic_site_key"), crs=traffic_gdf.crs)
    # transit access: bus stops within 1 km
    buf = sites[["traffic_site_key", "geometry"]].copy()
    buf["geometry"] = buf.geometry.buffer(1000)
    j = gpd.sjoin(bus_gdf[["geometry"]], buf, predicate="within", how="inner")
    cnt = j.groupby("traffic_site_key").size().rename("bus_count_1km").reset_index()
    sites = sites.merge(cnt, on="traffic_site_key", how="left")
    sites["bus_count_1km"] = sites["bus_count_1km"].fillna(0)

    def mm(s):
        rng = s.max() - s.min()
        return (s - s.min()) / rng if rng else 0.0
    sites["traffic_burden"]   = mm(sites["mean_daily_traffic"])
    sites["transit_deficit"]  = 1 - mm(sites["bus_count_1km"])
    sites["vulnerability"]    = 0.6 * sites["traffic_burden"] + 0.4 * sites["transit_deficit"]
    return sites.sort_values("vulnerability", ascending=False)

traffic_vuln = traffic_site_summary(traffic_gdf, bus_stops)
print("Traffic-location vulnerability ranking:")
display(traffic_vuln.drop(columns="geometry"))
traffic_vuln.drop(columns="geometry").to_csv(OUTPUT_DIR / "traffic_vulnerability.csv", index=False)

# %% [16b] 교통 취약지점 ← 속한 tract 형평성 결합
traffic_vuln_eq = gpd.sjoin(
    traffic_vuln.to_crs(WORK_CRS),
    acs_study[[COL["geoid"], "county_name", COL["medinc"],
               "pct_poverty", "pct_no_vehicle", "geometry"]],
    how="left", predicate="within").drop(columns="index_right")

def mm(s):
    s = s.astype(float); rng = s.max() - s.min()
    return (s - s.min()) / rng if rng else 0.0

# 1) 먼저 0~1로 정규화된 지표들을 만든다 (순서 중요)
traffic_vuln_eq["poverty"]    = mm(traffic_vuln_eq["pct_poverty"])      # 빈곤율 → 0~1
traffic_vuln_eq["no_vehicle"] = mm(traffic_vuln_eq["pct_no_vehicle"])   # 차량없음 → 0~1
traffic_vuln_eq["low_income"] = 1 - mm(traffic_vuln_eq[COL["medinc"]])  # 소득낮을수록 ↑

# 2) MEDHHINC 결측 tract 보완: low_income이 비면 '정규화된 poverty'로 채운다.
#    (pct_poverty 같은 퍼센트값이 아니라 0~1 스케일의 poverty로 채워야 함)
traffic_vuln_eq["low_income"] = traffic_vuln_eq["low_income"].fillna(
    traffic_vuln_eq["poverty"])

# 3) 사회적 취약성 = 세 지표의 평균 (모두 0~1)
traffic_vuln_eq["social_vuln"] = (traffic_vuln_eq["low_income"]
                                  + traffic_vuln_eq["no_vehicle"]
                                  + traffic_vuln_eq["poverty"]) / 3

# 4) 최종 복합 취약지수 = 교통·대중교통(기존) + 사회적 취약성(신규)
traffic_vuln_eq["composite_vuln"] = (0.4*traffic_vuln_eq["vulnerability"]
                                     + 0.6*traffic_vuln_eq["social_vuln"])
traffic_vuln_eq.sort_values("composite_vuln", ascending=False, inplace=True)

# NaN 점검: 모든 교통지점이 tract에 매칭됐는지 확인
n_unmatched = traffic_vuln_eq[COL["geoid"]].isna().sum()
print(f"tract 미매칭 교통지점: {n_unmatched}개 (0이어야 정상)")
# social_vuln이 0~1 범위인지 점검 (버그 재발 방지)
print(f"social_vuln 범위: {traffic_vuln_eq['social_vuln'].min():.3f} "
      f"~ {traffic_vuln_eq['social_vuln'].max():.3f} (0~1이어야 정상)")
display(traffic_vuln_eq.drop(columns="geometry"))
traffic_vuln_eq.drop(columns="geometry").to_csv(OUTPUT_DIR/"composite_vulnerability.csv", index=False)

# %% [16c] 정책 what-if 시나리오 — 공통 설정
# 모든 시나리오는 traffic_vuln_eq(교통지점 + tract 형평성)를 기반으로
# '지수 재계산'만 수행한다 (모델 재학습 없음). 따라서 빠르고 투명하다.
import numpy as np

# 원본 보존용 복사본 (시나리오마다 깨끗한 출발점에서 시작)
base = traffic_vuln_eq.drop(columns="geometry").copy().reset_index(drop=True)

# 정규화 함수 (원본 분포 기준으로 고정해 시나리오 간 비교 가능하게 함)
def mm_fixed(s, lo, hi):
    return 0.0 if hi == lo else (s - lo) / (hi - lo)

# 원본 분포의 min/max를 저장 (시나리오가 이 스케일을 공유)
TRAFFIC_LO, TRAFFIC_HI = base["mean_daily_traffic"].min(), base["mean_daily_traffic"].max()
BUS_LO, BUS_HI = base["bus_count_1km"].min(), base["bus_count_1km"].max()

def recompute_index(df):
    """교통량·버스수가 바뀐 df로 vulnerability·composite_vuln을 재계산."""
    df = df.copy()
    df["traffic_burden"]  = df["mean_daily_traffic"].apply(lambda v: mm_fixed(v, TRAFFIC_LO, TRAFFIC_HI))
    df["transit_deficit"] = 1 - df["bus_count_1km"].apply(lambda v: mm_fixed(v, BUS_LO, BUS_HI))
    df["vulnerability"]   = 0.6*df["traffic_burden"] + 0.4*df["transit_deficit"]
    df["composite_vuln"]  = 0.4*df["vulnerability"] + 0.6*df["social_vuln"]
    return df

print("기준선(현재 상태) 복합취약지수 상위 5:")
print(base[["LOCALNAM","county_name","mean_daily_traffic","bus_count_1km",
            "social_vuln","composite_vuln"]]
      .sort_values("composite_vuln", ascending=False).head().to_string(index=False))

# %% [16d] 시나리오 1 — 대중교통 확충 (transit expansion)
# 복합취약지수 상위 N개 지점의 1km 내 버스정류장을 K개 추가하면
# transit_deficit과 composite_vuln이 얼마나 감소하는가?
def scenario_transit_expansion(base, top_n=3, add_stops=10):
    df = base.copy()
    targets = df.sort_values("composite_vuln", ascending=False).head(top_n).index
    df.loc[targets, "bus_count_1km"] = df.loc[targets, "bus_count_1km"] + add_stops
    return recompute_index(df), targets

for k in [5, 10, 20]:
    s1, tgt = scenario_transit_expansion(base, top_n=3, add_stops=k)
    delta = base.loc[tgt, "composite_vuln"].values - s1.loc[tgt, "composite_vuln"].values
    print(f"[정류장 +{k}개, 상위3지점] 평균 복합취약지수 감소: {delta.mean():.3f}")

# 대표 시나리오(+10) 상세 표
s1, tgt = scenario_transit_expansion(base, top_n=3, add_stops=10)
comp = base.loc[tgt, ["LOCALNAM","composite_vuln"]].copy()
comp["composite_vuln_after"] = s1.loc[tgt, "composite_vuln"].values
comp["reduction"] = comp["composite_vuln"] - comp["composite_vuln_after"]
print("\n시나리오1 상세 (정류장 +10):")
print(comp.to_string(index=False))
s1.to_csv(OUTPUT_DIR/"scenario1_transit_expansion.csv", index=False)

# %% [16e] 시나리오 2 — 교통 수요 관리 (traffic demand reduction)
# 재택근무·통행료 등으로 상위 지점의 일교통량을 10/20/30% 감축하면?
def scenario_traffic_reduction(base, top_n=3, pct=0.2):
    df = base.copy()
    targets = df.sort_values("traffic_burden", ascending=False).head(top_n).index
    df.loc[targets, "mean_daily_traffic"] = df.loc[targets, "mean_daily_traffic"] * (1 - pct)
    return recompute_index(df), targets

for p in [0.10, 0.20, 0.30]:
    s2, tgt = scenario_traffic_reduction(base, top_n=3, pct=p)
    delta = base.loc[tgt, "vulnerability"].values - s2.loc[tgt, "vulnerability"].values
    print(f"[교통량 -{int(p*100)}%, 상위3지점] 평균 vulnerability 감소: {delta.mean():.3f}")

s2, _ = scenario_traffic_reduction(base, top_n=3, pct=0.20)
s2.to_csv(OUTPUT_DIR/"scenario2_traffic_reduction.csv", index=False)

# %% [16f] 시나리오 3 — 한정 예산 배분: 효율 우선 vs 형평 우선 (개선판)
# 같은 예산(정류장 K개)을 어디에 투입하느냐로 결과가 어떻게 갈리는지 비교한다.
#   (a) 효율 우선: 교통부담(traffic_burden) 최고 지점에 배분
#   (b) 형평 우선: 사회적 취약성(social_vuln) 최고 지점에 배분
# 측정은 '전체 평균'이 아니라 (1)배분 타깃의 개선폭, (2)가장 취약한 지점의
# 보호 효과로 본다. 전체 평균은 11개 지점에 희석돼 차이가 안 드러나기 때문.

ADD_STOPS = 5   # 현실적인 소규모 확충 (이전 15는 과대)

def allocate(base, mode, add_stops=ADD_STOPS):
    df = base.copy()
    idx = (df["traffic_burden"].idxmax() if mode == "efficiency"
           else df["social_vuln"].idxmax())
    df.loc[idx, "bus_count_1km"] += add_stops
    return recompute_index(df), idx

eff, i_eff = allocate(base, "efficiency")
equ, i_equ = allocate(base, "equity")

# 기준선에서 '가장 취약한 지점'(보호해야 할 대상)
worst_idx = base["composite_vuln"].idxmax()
worst_name = base.loc[worst_idx, "LOCALNAM"]

def summarize(label, scen, target_idx):
    return {
        "allocation": label,
        "target": base.loc[target_idx, "LOCALNAM"],          # 예산 투입 지점
        "target_before": base.loc[target_idx, "composite_vuln"],
        "target_after":  scen.loc[target_idx, "composite_vuln"],
        "target_reduction": base.loc[target_idx, "composite_vuln"] - scen.loc[target_idx, "composite_vuln"],
        # 가장 취약한 지점(worst)이 이 배분으로 얼마나 보호되나
        "worst_after": scen.loc[worst_idx, "composite_vuln"],
        # 전체 취약 인구 보호 관점: 전체 합계(낮을수록 좋음)
        "total_composite": scen["composite_vuln"].sum(),
    }

rows = [
    {"allocation":"baseline","target":"-",
     "target_before":base.loc[worst_idx,"composite_vuln"],
     "target_after":base.loc[worst_idx,"composite_vuln"],
     "target_reduction":0.0,
     "worst_after":base.loc[worst_idx,"composite_vuln"],
     "total_composite":base["composite_vuln"].sum()},
    summarize("efficiency", eff, i_eff),
    summarize("equity",     equ, i_equ),
]
s3 = pd.DataFrame(rows)

print(f"가장 취약한 지점(보호 대상): {worst_name} "
      f"(기준 composite={base.loc[worst_idx,'composite_vuln']:.3f})\n")
print(f"정류장 +{ADD_STOPS}개 배분 비교:")
print(s3.to_string(index=False))

print("\n해석 포인트:")
print(f" • 효율 우선은 {base.loc[i_eff,'LOCALNAM']}(교통최다)에 투입 → "
      f"그 지점만 {s3.loc[1,'target_reduction']:.3f} 개선, "
      f"가장 취약한 {worst_name}은 {s3.loc[1,'worst_after']:.3f}로 그대로.")
print(f" • 형평 우선은 {base.loc[i_equ,'LOCALNAM']}(최취약)에 투입 → "
      f"가장 취약한 지점을 {s3.loc[2,'worst_after']:.3f}로 직접 낮춤.")
print(" • 같은 예산이라도 형평 배분이 '가장 취약한 집단'을 직접 보호한다.")

s3.to_csv(OUTPUT_DIR/"scenario3_allocation.csv", index=False)

# %% [16g] 시나리오 4 — 인구가중 노출 (population-weighted exposure)
# '지점이 취약'을 넘어 '얼마나 많은 사람이 영향받는가'로 환산.
# 각 교통지점이 속한 tract의 인구를 가중치로 사용.
# (acs_study에 tract 인구 TOTALPOP이 있으므로 지점-tract 매칭으로 가져온다.)
pop_lookup = acs_study[[COL["geoid"], COL["pop"]]].rename(
    columns={COL["geoid"]:"GEOID20_pop", COL["pop"]:"tract_pop"})
expo = base.merge(pop_lookup, left_on=COL["geoid"], right_on="GEOID20_pop", how="left")
expo["tract_pop"] = expo["tract_pop"].fillna(expo["tract_pop"].median())

# 노출 점수 = 복합취약지수 × tract 인구
expo["exposure_score"] = expo["composite_vuln"] * expo["tract_pop"]
expo_sorted = expo.sort_values("exposure_score", ascending=False)
print("인구가중 노출 상위 5 (많은 인구 × 높은 취약):")
print(expo_sorted[["LOCALNAM","county_name","tract_pop",
                   "composite_vuln","exposure_score"]].head().to_string(index=False))
expo_sorted[["LOCALNAM","county_name","tract_pop","composite_vuln","exposure_score"]].to_csv(
    OUTPUT_DIR/"scenario4_population_exposure.csv", index=False)

# %% [17] Map: traffic vulnerability + EPA stations + bus stops
fig, ax = plt.subplots(figsize=(9, 9))
bus_stops.plot(ax=ax, color="0.7", markersize=3, alpha=0.4, label="LYNX bus stops")
tv = traffic_vuln.to_crs(WORK_CRS)
tv.plot(ax=ax, column="vulnerability", cmap="OrRd", markersize=160,
        edgecolor="k", legend=True, legend_kwds={"label": "Vulnerability index"})
pm25_sites.plot(ax=ax, color="blue", marker="*", markersize=220, label="PM2.5 stations")
no2_sites.plot(ax=ax, color="green", marker="^", markersize=120, label="NO2 stations")
for _, r in tv.iterrows():
    ax.annotate(r["LOCALNAM"], (r.geometry.x, r.geometry.y), fontsize=7, xytext=(4, 4),
                textcoords="offset points")
ax.set_title("Orlando metro — traffic vulnerability, transit access & air-quality stations")
ax.set_axis_off(); ax.legend(loc="lower left")
plt.tight_layout(); plt.savefig(OUTPUT_DIR / "vulnerability_map.png", dpi=200); plt.show()

# %% [18] Persist model-performance tables and the full modelling datasets
pm25_res.assign(pollutant="PM2.5").to_csv(OUTPUT_DIR / "model_results_pm25.csv", index=False)
no2_res.assign(pollutant="NO2").to_csv(OUTPUT_DIR / "model_results_no2.csv", index=False)
if not pm25_fi.empty: pm25_fi.to_csv(OUTPUT_DIR / "importance_pm25.csv", index=False)
if not no2_fi.empty:  no2_fi.to_csv(OUTPUT_DIR / "importance_no2.csv", index=False)
pm25_data.to_csv(OUTPUT_DIR / "modeling_table_pm25.csv", index=False)
no2_data.to_csv(OUTPUT_DIR / "modeling_table_no2.csv", index=False)

# GeoPackage with all spatial layers for QGIS/ArcGIS
gpkg = OUTPUT_DIR / "spatial_layers.gpkg"
traffic_vuln.to_file(gpkg, layer="traffic_vulnerability", driver="GPKG")
pm25_sites.to_file(gpkg, layer="pm25_stations", driver="GPKG")
no2_sites.to_file(gpkg, layer="no2_stations", driver="GPKG")
print("Saved spatial layers to", gpkg)

# %% [19] List outputs and zip for download
print("Generated files in", OUTPUT_DIR.resolve(), ":")
for f in sorted(OUTPUT_DIR.iterdir()):
    print("  -", f.name, f"({f.stat().st_size/1024:.1f} KB)")

zip_path = shutil.make_archive("korus70_outputs", "zip", OUTPUT_DIR)
print("\nZipped ->", zip_path)
try:
    from google.colab import files
    files.download(zip_path)
except Exception:
    print("Not in Colab: download korus70_outputs.zip from the file browser.")

"""## Final deliverable files

Running every cell produces, in `outputs/` (zipped as `korus70_outputs.zip`):

| File | What it is |
|---|---|
| `model_results_pm25.csv` / `model_results_no2.csv` | RMSE / MAE / R² for Baseline, Ridge, RandomForest, XGBoost |
| `importance_pm25.csv` / `importance_no2.csv` | permutation importances (test set) |
| `modeling_table_pm25.csv` / `modeling_table_no2.csv` | the full (station×day) feature tables — fully reproducible |
| `pm25_importance.png` / `no2_importance.png` | importance bar charts |
| `pm25_pred_vs_actual.png` / `no2_pred_vs_actual.png` | held-out time-series fit |
| `traffic_vulnerability.csv` | ranked traffic-location vulnerability index |
| `vulnerability_map.png` | combined map figure |
| `spatial_layers.gpkg` | GeoPackage (traffic vuln + EPA stations) for QGIS/ArcGIS |

### What you can honestly claim from this
- A **temporal** PM2.5 / NO2 model per station, validated on a held-out later period, beating a mean baseline.
- Defensible **permutation** importances (e.g., the relative role of weather vs. traffic vs. seasonality).
- A transparent, **descriptive** vulnerability map combining traffic burden and transit deficit.

### What you should NOT claim
- That the model explains **spatial** differences between neighbourhoods (too few stations).
- Causal statements ("more traffic *causes* X µg/m³"). These are associations.

"""

